steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/anan-project/blog/app:$COMMIT_SHA'
      - '.'

  # push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/anan-project/blog/app:$COMMIT_SHA'

  # deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy blog \
          --image us-west1-docker.pkg.dev/anan-project/blog/app:$COMMIT_SHA \
          --region us-west1 \
          --platform managed \
          --port 3000 \
          --update-env-vars MICROCMS_SERVICE_DOMAIN=${_MICROCMS_SERVICE_DOMAIN} \
          --update-secrets MICROCMS_API_KEY=MICROCMS_API_KEY:latest

images:
  - 'us-west1-docker.pkg.dev/anan-project/blog/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
