 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia-northeast1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'blog'
   - '--image'
   - 'asia-northeast1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA'
   - '--region'
   - 'asia-northeast1'
 images:
 - 'asia-northeast1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA'
