steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '--no-cache'
  - 'us-west1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA'
  - --build-arg=microcms_api_key=$$MICROCMS_API_KEY
  - --build-arg=microcms_service_domain=${_MICROCMS_SERVICE_DOMAIN}
  - --build-arg=next_public_api_endpoint=${_NEXT_PUBLIC_API_ENDPOINT}
  - '.'
  secretEnv: ["MICROCMS_API_KEY"]
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'blog'
  - '--image'
  - 'us-west1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA'
  - '--region'
  - 'us-west1'
images:
- 'us-west1-docker.pkg.dev/anan-project/blog/next:$COMMIT_SHA'
availableSecrets:
  secretManager:
    - versionName: projects/anan-project/secrets/MICROCMS_API_KEY/versions/latest
      env: MICROCMS_API_KEY
